title: "Steven Villalon's Data Science Portfolio"
theme: jekyll-theme-slate
description: "Showcasing my data science projects and achievements."
baseurl: ""
url: "https://stevenvillalon.github.io/portfoliosite/"